package client;

public interface GameConstants {
	int PLAYER1 = 0, PLAYER2 =1;
	int GREATBALL = 0, ULTRABALL =1, MASTERBALL = 2, ATTACK1 = 3, ATTACK2 = 4, ATTACK3 = 5, ATTACK4 = 6, ATTACK5 = 7, TIMEMACHINE = 8, FLY = 9,
			POTION = 10, POKEDOLL = 11;
	int MYSTERYDUNGEON = 0, CHANCE = 1, HEAL = 2, TRADE =3, FIGHT = 4, TAKE1 = 5, TAKE2 = 6, TAKE3 = 7;
}
